version: "3.9"
services:
  screamlark-bot:
    build: .
    container_name: screamlark-bot
    environment:
      - BOT_NAME=${BOT_NAME}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - GPT_KEY=${GPT_KEY}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - CHANNEL_NAME=${CHANNEL_NAME}
      - CHELOVCHIK_BOT_URL=${CHELOVCHIK_BOT_URL}
      - CHELOVCHIK_BOT_TOKEN=${CHELOVCHIK_BOT_TOKEN}
    volumes:
      - ./data:/data
      - ./log:/log
    restart: unless-stopped
